/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/user": {
    /** Testing */
    get: {
      parameters: {};
      responses: {
        default: {
          schema: definitions["User"][];
        };
      };
    };
  };
}

export interface definitions {
  User: {
    password?: string;
    proof?: string;
    id?: number;
    date_modified?: string;
    active?: boolean;
    confirmed_at?: string;
    email?: string;
    last_name?: string;
    first_name?: string;
    date_created?: string;
  };
}

export interface operations {}

export interface external {}
